USE BOLETA_SUGERENCIA;
create database boleta_sugerencia;

create table sugerencia_aceptada(
NO int(11),
IDSUGERENCIA INT(7),
CODIGO INT(7),
EXPEDIENTE INT (7),
PRIMER_NOMBRE VARCHAR(20),
SEGUNDO_NOMBRE VARCHAR(20),
PRIMER_APELLIDO VARCHAR(20),
SEGUNDO_APELLIDO VARCHAR(20),
DPI INT(13),
CORREO VARCHAR(60),
TELEFONO INT(8),
SEXO varchar(5),
PROFESION VARCHAR(60),
DIRECCION VARCHAR (150),
SUGERENCIA VARCHAR(700),
FECHARECIBIDO DATE,
IDTIPOASOCIADO INT (7),
IDSOLICITUDENVIO VARCHAR(2),
IDCLASIFICACION VARCHAR(2),
TIPO_RESPUESTA_GERENCIA VARCHAR(2)
); ALTER TABLE SUGERENCIA_ACEPTADA ADD primary key (IDSUGERENCIA);



CREATE TABLE USUARIO(
NO INT(7),
IDUSUARIO VARCHAR(100),
NOMBRE VARCHAR(150),
DESCRIPCION VARCHAR(300),
CORREO VARCHAR(60),
FECHAALTA DATE,
FECHABAJA DATE,
PASSWORD BLOB,
IDTIPOUSUARIO varchar(2),
IDESTADO VARCHAR(2)
); ALTER TABLE USUARIO ADD PRIMARY KEY (IDUSUARIO);

create table TIPO_USUARIO(
NO INT(8),
IDTIPOUSUARIO VARCHAR(2) PRIMARY KEY,
NOMBRE VARCHAR(150),
DESCRIPCION VARCHAR(250),
PERMISOS VARCHAR(250)
); ALTER TABLE USUARIO ADD CONSTRAINT FK_USUARIO_TIPOUSUARIO FOREIGN KEY(IDTIPOUSUARIO) REFERENCES TIPO_USUARIO(IDTIPOUSUARIO);

CREATE TABLE ESTADO_USUARIO(
NO INT(8),
IDESTADO VARCHAR(2),
NOMBRE VARCHAR(150),
DESCRIPCION VARCHAR(250)
); ALTER TABLE ESTADO_USUARIO ADD PRIMARY KEY (IDESTADO);
 ALTER TABLE USUARIO ADD CONSTRAINT FK_ESTADOUSUARIO_USUARIO FOREIGN KEY(IDESTADO) REFERENCES ESTADO_USUARIO(IDESTADO);

CREATE TABLE BITACORA(
NO INT(7),
IDBITACORA VARCHAR(100) primary KEY,
IDUSUARIO varchar(100),
FECHAINICIO DATE,
FECHAFINAL DATE,
CAMPOAFECTADO VARCHAR (500),
DETALLESINMODIFICAR varchar(500),
DETALLEMODIFICADO VARCHAR(500),
OBSERVACIONES VARCHAR(500)
); ALTER TABLE BITACORA ADD CONSTRAINT FK_USUARIO_BITACORA FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO(IDUSUARIO);

CREATE TABLE REGISTRO_LOCAL(
NO INT(11),
CODIGO INT(7) PRIMARY KEY,
EXPEDIENTE INT (7),
PRIMER_NOMBRE VARCHAR(20),
SEGUNDO_NOMBRE VARCHAR(20),
PRIMER_APELLIDO VARCHAR(20),
SEGUNGO_APELLIDO VARCHAR(20),
DPI BIGINT(16),
CORREO VARCHAR(25),
IDTIPOASOCIADO INT(7),
IDESTADO INT(3)
);


CREATE TABLE CLASIFICACION_SUGERENCIA(
NO INT(8),
IDCLASIFICACION VARCHAR(2),
NOMBRE VARCHAR(30),
DESCRIPCION VARCHAR(250)
); ALTER TABLE CLASIFICACION_SUGERENCIA ADD PRIMARY KEY (IDCLASIFICACION);
ALTER TABLE SUGERENCIA_ACEPTADA ADD CONSTRAINT FK_CLASIFICACIONSUGERENCIA_SUGERENCIAACEPTADA foreign key (IDCLASIFICACION) REFERENCES CLASIFICACION_SUGERENCIA(IDCLASIFICACION);

create table TIPO_ASOCIADO(
NO int(8),
IDTIPOASOCIADO INT(7),
NOMBRE varchar(50),
DESCRIPCION VARCHAR(250)
); ALTER TABLE TIPO_ASOCIADO ADD PRIMARY KEY(IDTIPOASOCIADO);

ALTER TABLE SUGERENCIA_ACEPTADA ADD CONSTRAINT FK_TIPOASOCIADO_SUGERENCIAACEPTADA foreign key (IDTIPOASOCIADO) REFERENCES TIPO_ASOCIADO(IDTIPOASOCIADO);

CREATE TABLE SOLICITUD_ENVIO(
NO INT(11),
IDSOLICITUDENVIO VARCHAR(2) PRIMARY KEY,
NOMBRE VARCHAR(50),
DESCRIPCION VARCHAR(250)
);
ALTER TABLE SUGERENCIA_ACEPTADA ADD CONSTRAINT FK_SOLICITUDENVIO_SUGERENCIAACEPTADA foreign key (IDSOLICITUDENVIO) REFERENCES SOLICITUD_ENVIO(IDSOLICITUDENVIO);

CREATE TABLE TIPO_RESPUESTA_GERENCIA(
NO INT(8),
IDTIPORESPUESTAGERENCIA VARCHAR(7) primary KEY,
NOMBRE VARCHAR(100),
DESCRIPCION varchar(200)
);
ALTER TABLE SUGERENCIA_ACEPTADA DROP column TIPO_RESPUESTA_GERENCIA;
ALTER TABLE SUGERENCIA_ACEPTADA ADD column IDTIPORESPUESTAGERENCIA VARCHAR(7) AFTER IDCLASIFICACION;
ALTER TABLE SUGERENCIA_ACEPTADA ADD constraint FK_TIPORESPUESTAGERENCIA_SUGERENCIAACEPTADA FOREIGN KEY (IDTIPORESPUESTAGERENCIA) REFERENCES TIPO_RESPUESTA_GERENCIA(IDTIPORESPUESTAGERENCIA);



insert into tipo_usuario values (0,'A','Administrador','Usuario administrador. No tiene limites en el manejo de la aplicación, este se encuentra por encima de cualquier otro tipo de usuario.','Consultas, Inserciones, Usuarios, Reportes, Bitácoras. Sesiones');
insert into tipo_usuario values (1,'B','Usuario Avanzado','Usuario avanzado. Tiene ciertas limitaciones en el manejo de la app, no podra ver vitacoras, crear o administrar usuarios, pero podra generar reportes, realizar inserciones, consultar entre otras cosas.','Consultas, Inserciones, Reportes');
insert into tipo_usuario values (2,'C','Usuario Consulta','Usuario consulta. Este usuario se encuentra limitado a únicamente realizar consultas de las boletas registradas e ingresadas.','Consulta');

INSERT INTO usuario VALUES (0,'cristofer.estrada','Cristofer Estrada','Administrador del Sistema','cristofer.estrada@asapeespu.com','2021-03-02','0000-00-00',AES_ENCRYPT('asaitce','123456'),'A','A');
INSERT INTO usuario VALUES (1,'byroncastillo','Byron Castillo','Miembro de la Comision de Disciplina',AES_ENCRYPT('castillopezbyron@gmail.com','123456'),'2021-03-04','0000-00-00',AES_ENCRYPT('byron2021','123456'),'B','A');





USE BOLETA_SUGERENCIA;
create table MUNICIPIO(
NO int,
IDMUNICIPIO INT PRIMARY KEY,
NOMBRE VARCHAR (250),
DESCRIPCION varchar(250),
IDDEPARTAMENTO INT
);

CREATE TABLE DEPARTAMENTO(
NO INT,
IDDEPARTAMENTO INT PRIMARY KEY,
NOMBRE varchar(250),
DESCRIPCION VARCHAR(250)
);
ALTER TABLE MUNICIPIO ADD CONSTRAINT FK_MUNICIPIOS_DEPARTAMENTOS FOREIGN KEY (IDDEPARTAMENTO) REFERENCES DEPARTAMENTO(IDDEPARTAMENTO);
ALTER TABLE sugerencia_aceptada ADD column IDMUNICIPIO int;
ALTER TABLE sugerencia_aceptada ADD CONSTRAINT FK_MUNUCIPIO_BOLETAACEPTADA FOREIGN KEY (MUNICIPIO) REFERENCES MUNICIPIO(IDMUNICIPIO);


CREATE TABLE DEPARTAMENTO



